# Train/val sets
path: "./training_data"  # dataset root dir
train: train/  # train images (relative to 'path'), can add more by listing
val: val/  # val images (relative to 'path'), can add more by listing
test:  # test images (optional)

# Classes 
names:
  0: defect
  1: out-of-focus